### ISSUE TITLE
Spring to Conda

### ISSUE THREAD

**Issue by KamilSJaron** [shubhamchandak94/Spring#18]
Hello, thanks for spring. The speed and compress ratio sounds amazing.

Did you consider submitting it to conda? That would make the program so much more accessible.

**Comment by shubhamchandak94** [comment]
Thanks for the suggestion. We'll look into the possibility.
Shubham

**Comment by KamilSJaron** [comment]
Hi there, I am looking at it now and I think I will be able to submit Spring to bioconda, the only thing I would need from you is to make a tagged GitHub release. Do you think you could do that?

**Comment by shubhamchandak94** [comment]
Thanks for the kind offer, however I would prefer to do it myself (mainly to learn the procedure). I plan to work on this in the next few days and I'll keep you posted. I am assuming that I should follow the instructions from https://bioconda.github.io/contributor/guidelines.html

**Comment by KamilSJaron** [comment]
Yeah, you need two files.

`build.sh` file, that will look moreless like this:

```
#!/bin/bash

mkdir -p $PREFIX/bin
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${PREFIX} ..
make
make install
```

and a configuration file (`meta.yaml`) were all the meta information will be... I got this far with that one:

```
{% set name = "Spring" %}
{% set version = "TODO" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/shubhamchandak94/Spring/releases/download/{{ version }}/Spring-v{{ version }}.tar.gz
  sha256: TODO

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

test:
  commands:
    - spring -h

about:
  home: https://github.com/shubhamchandak94/Spring
  license: TODO
  license_file: license.pdf
  summary: Spring is a compression tool for Fastq files
```

Once a release is out, you just add url to the tarball, calculate it's hash to verify successful dl and that's kind of it.

One thing that might be problematic is the restrictive license you have chosen for your software. It imposes a lot of constants on usage and mainly it's not a standard open source license, so I am not sure if conda will like that.
